In [31]:
import numpy as np

In [32]:
class Perceptron(object):
    
# initialization code
    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        self.loss_lst = []
    
# Activation function code which is a simple step function
    def activation_fn(self, x):
        #return (x >= 0).astype(np.float32)
        return 1 if x >= 0 else 0

# Calculating dot product of W and X (input vector) and applying step function
    def predict(self, x):
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
# Perceptron Learning code running all the samples for given epochs or iterations
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.predict(x)
                e = d[i] - y
                self.W = self.W + self.lr * e * x
            self.loss_lst.append(e)                       

## for AND gate

In [33]:
if __name__ =='__main__' :
  X = np.array([[0,0],[0,1],[1,0],[1,1]])
  d = np.array([0,0,0,1]) #for and
  perceptron = Perceptron(input_size = 2)
  perceptron.fit(X,d)
  print(perceptron.W)

[-3.  2.  1.]


In [34]:
x=[1, 0, 1]
y= -3*1+2*0+1*1
y

-2

In [35]:
# import matplotlib.pyplot as plt
# x_axis = [int(x) for x in range(100)]
# y_axis = perceptron.loss_lst
# plt.plot(x_axis, y_axis)
# plt.xlabel("iteration")
# plt.ylabel("loss")
# plt.show()

for OR gate

In [40]:
if __name__ =='__main__' :
  X = np.array([[0,0],[0,1],[1,0],[1,1]])
  d = np.array([0,1,1,1])
  perceptron = Perceptron(input_size = 2)
  perceptron.fit(X,d)
  print(perceptron.W)

[-1.  1.  1.]


In [37]:
x1=[1, 0, 1]
y1= -3*-1+2*1+1*1
y1

6

In [38]:
# for XOR
if __name__ =='__main__' :
  X = np.array([[0,0],[0,1],[1,0],[1,1]])
  d = np.array([0,1,1,0])
  perceptron = Perceptron(input_size = 2)
  perceptron.fit(X,d)
  print(perceptron.W)


[ 0. -1.  0.]


In [39]:
x2=[1, 0, 1]
y2= -3*0+2*-1+1*0
y2

-2